use_frameworks!

platform :ios, '10.0'

target 'XROCSupport_Example' do
  pod 'XROCSupport', :path => '../'
  pod 'Masonry', '1.1.0'
  pod 'ReactiveObjC', '3.1.1'
  

  target 'XROCSupport_Tests' do
    inherit! :search_paths

    
  end
end
